In [22]:
import numpy as np

In [2]:
a = np.random.randint(50, size = (1000, ))
ans = np.zeros((1000,))
ans[np.random.randint(low = 0, high = 1000)] = 1
print(np.argmax(ans))

67


In [27]:
ab = [1, 2]
bc = [2]
cd = [3]
abb, bcc, cdd = np.array([ab, bc, cd])
print(abb, bcc, cdd)

[1, 2] [2] [3]


In [3]:
b = -np.sum(np.log(np.exp(a)/np.sum(np.exp(a), axis = 0)) * ans, axis = 0)
print(b, ans, ans*b)

26.27784281046012 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [4]:
%timeit -n 15000 k = -np.sum(np.log(np.exp(a)/np.sum(np.exp(a), axis = 0)), axis = 0)
%timeit -n 15000 k = -np.log(np.exp(a) / np.sum(np.exp(a), axis = 0))[np.argmax(ans)]

26.2 µs ± 394 ns per loop (mean ± std. dev. of 7 runs, 15000 loops each)
24.7 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 15000 loops each)


In [5]:
N = 10
D = 20
H = 25
C = 15
bef_input = np.random.random((N, D))
bef_weight = np.random.random((D, H))
bef_bias = np.random.random((H, ))

In [6]:
kk = np.ones((N, ))
aft_input = np.concatenate((bef_input, kk.reshape(-1, 1)), axis = 1)
aft_weight = np.concatenate((bef_weight, bef_bias.reshape(1, -1)), axis = 0)
aa = np.matmul(aft_input, aft_weight)
bb = np.matmul(bef_input, bef_weight) + bef_bias.T
# aa = np.zeros(())
# bb = np.arange(4, 10).reshape(2, -1)
# bb.shape

In [7]:
k = np.random.randint(10, size = (10, 10))
ans = np.random.randint(0, 10, size = 10)

In [8]:
print(k, ans)
np.sum(k[np.arange(k.shape[0]), ans], axis = 0)

[[4 1 7 4 1 3 7 4 7 0]
 [3 0 4 5 6 7 2 0 7 4]
 [0 6 2 6 0 8 3 9 1 8]
 [0 5 2 6 7 6 0 3 2 9]
 [5 8 7 5 5 7 1 3 3 8]
 [5 8 5 3 5 1 0 7 2 6]
 [9 2 4 5 3 6 2 9 4 7]
 [4 7 5 1 0 0 3 9 0 8]
 [2 3 4 1 3 2 3 2 0 1]
 [6 3 1 0 4 7 9 1 5 5]] [5 6 1 3 3 7 4 7 0 4]


47

In [9]:
scores_bef = np.random.randint(0, 20, size = (N, C))
y = np.random.randint(C, size = (N, ))
scores_bef, y

(array([[17, 17, 17,  8,  2,  5,  4, 18,  8, 10, 12, 15, 10,  0,  4],
        [ 2, 12,  4,  5, 16,  8,  4,  0,  4, 18, 18, 12, 19,  7, 17],
        [ 2,  1,  6,  7, 11,  3, 15, 12,  0,  7, 19, 11, 15,  5, 15],
        [18,  0,  9, 10,  1, 12,  4, 18,  4,  2, 10,  0,  0, 16,  8],
        [ 3,  2,  3,  3,  3, 10,  5, 11, 13, 19, 13,  1, 11, 16, 18],
        [11,  0, 17,  0, 17,  1,  3, 14,  8, 10,  5, 17, 12, 11, 18],
        [10, 11, 13,  8,  0,  1,  6, 15,  4,  0, 17, 13,  3, 16,  0],
        [ 4, 11, 18,  8, 12, 18,  2,  5, 19, 14, 13,  0, 19, 19,  6],
        [15, 15, 16, 19,  2, 18,  9, 18, 14, 12,  0,  1, 10,  1,  2],
        [ 6,  0, 18, 17,  4, 15,  5, 10,  0, 19, 16,  5,  7, 16,  9]]),
 array([10,  6,  7,  7,  3,  3,  0,  0,  2,  5]))

In [10]:
scores_bef = scores_bef - np.mean(scores_bef, axis = 1).reshape(-1, 1)
scores_bef = np.exp(scores_bef) / np.sum(np.exp(scores_bef), axis = 1).reshape(-1, 1)
asd = np.copy(scores_bef)
asd[np.arange(N), y] -= 1

In [11]:
qq = np.random.randint(10, size = (N-7, C-12))
pp = np.random.randint(10, size = (N-7, H-20))
print(qq, pp, sep = '\n')

[[9 3 3]
 [2 7 1]
 [0 8 4]]
[[6 5 9 4 1]
 [7 2 2 1 2]
 [2 2 3 7 5]]


In [12]:
qqq = np.random.randint(10, size = (5, 6, 7))
ppp = np.random.randint(10, size = (5, 7))
print(np.einsum('ijk, ik -> ij', qqq, ppp).shape)
vv = np.random.randint(0, 5, size = 3)
# vv

(5, 6)


In [13]:
aas = np.where(qq>=7)
print(aas, qqq[aas[0], aas[1], aas[1]], qqq, sep = '\n')

(array([0, 1, 2]), array([0, 1, 1]))
[0 3 2]
[[[0 5 3 3 6 3 1]
  [0 8 0 4 1 4 9]
  [0 2 1 9 0 0 4]
  [5 0 1 7 6 2 8]
  [9 3 0 5 9 6 1]
  [3 7 6 8 0 4 8]]

 [[7 4 8 2 9 9 7]
  [0 3 9 8 9 7 6]
  [9 2 6 0 7 7 7]
  [5 1 6 4 5 8 4]
  [1 5 8 6 9 0 3]
  [6 9 4 2 1 0 8]]

 [[5 7 1 4 0 6 8]
  [6 2 4 7 5 8 1]
  [9 7 9 2 3 8 4]
  [0 1 2 2 3 5 8]
  [4 4 5 7 9 9 7]
  [8 6 5 3 0 9 1]]

 [[9 7 8 8 8 4 7]
  [2 3 9 8 1 9 1]
  [2 2 0 6 9 1 3]
  [5 8 9 7 9 3 6]
  [2 5 0 4 6 1 4]
  [3 4 2 8 8 3 0]]

 [[5 7 3 3 1 4 6]
  [1 4 4 7 1 3 1]
  [4 7 8 5 3 6 3]
  [1 9 1 0 7 5 9]
  [7 4 5 3 9 8 9]
  [1 6 7 1 5 3 9]]]


In [14]:
t = np.einsum('ij, ik -> ijk', pp, qq)
print(t, t.shape, sep = '\n')

[[[54 18 18]
  [45 15 15]
  [81 27 27]
  [36 12 12]
  [ 9  3  3]]

 [[14 49  7]
  [ 4 14  2]
  [ 4 14  2]
  [ 2  7  1]
  [ 4 14  2]]

 [[ 0 16  8]
  [ 0 16  8]
  [ 0 24 12]
  [ 0 56 28]
  [ 0 40 20]]]
(3, 5, 3)


In [15]:
ttv = np.einsum('ij, ik -> ikj', qq, pp)
print(ttv, ttv.shape, sep = '\n')

[[[54 18 18]
  [45 15 15]
  [81 27 27]
  [36 12 12]
  [ 9  3  3]]

 [[14 49  7]
  [ 4 14  2]
  [ 4 14  2]
  [ 2  7  1]
  [ 4 14  2]]

 [[ 0 16  8]
  [ 0 16  8]
  [ 0 24 12]
  [ 0 56 28]
  [ 0 40 20]]]
(3, 5, 3)


In [16]:
np.sum(t, axis = 0).shape

(5, 3)

In [17]:
ttaa = [[1, 2, 3, 4], [3, 4, 5, 6]]
ttaa = ttaa - np.mean(ttaa, axis = 1).reshape(-1, 1)
# np.sum(np.exp(ttaa), axis = 1).reshape(-1, 1)
np.exp(ttaa) / np.sum(np.exp(ttaa), axis = 1).reshape(-1, 1)

array([[0.0320586 , 0.08714432, 0.23688282, 0.64391426],
       [0.0320586 , 0.08714432, 0.23688282, 0.64391426]])

In [18]:
output2_grad = asd
W2 = np.random.randint(-5, 5, size = (H, C))

In [19]:
activate_first_layer_grad = np.zeros(shape = (N, H, H))
diag_check = np.where(asd >= 0) # Extracting only positive values' indices.
activate_first_layer_grad[diag_check[0], diag_check[1], diag_check[1]] = 1 # Size : (N, H, H)
print(asd, activate_first_layer_grad, sep = '\n===================================================\n')

[[ 1.70577536e-01  1.70577536e-01  1.70577536e-01  2.10509403e-05
   5.21800641e-08  1.04806460e-06  3.85561421e-07  4.63677817e-01
   2.10509403e-05  1.55546579e-04 -9.98850658e-01  2.30851592e-02
   1.55546579e-04  7.06180376e-09  3.85561421e-07]
 [ 2.15315645e-08  4.74264268e-04  1.59097938e-07  4.32473033e-07
   2.58939517e-02  8.68645307e-06 -9.99999841e-01  2.91398038e-09
   1.59097938e-07  1.91331861e-01  1.91331861e-01  4.74264268e-04
   5.20093922e-01  3.19556750e-06  7.03870583e-02]
 [ 3.91837227e-08  1.44148860e-08  2.13935877e-06  5.81538007e-06
   3.17508993e-04  1.06512401e-07  1.73354037e-02 -9.99136921e-01
   5.30294020e-09  5.81538007e-06  9.46480970e-01  3.17508993e-04
   1.73354037e-02  7.87026108e-07  1.73354037e-02]
 [ 4.67583460e-01  7.12128662e-09  5.77043832e-05  1.56856776e-04
   1.93576640e-08  1.15902352e-03  3.88809075e-07 -5.32416540e-01
   3.88809075e-07  5.26195863e-08  1.56856776e-04  7.12128662e-09
   7.12128662e-09  6.32805400e-02  2.12282562e-05]
 [ 7

In [20]:
z2_grad = np.matmul(output2_grad, W2.T) * (bb > 0)
print(activate_first_layer_grad * (vv > 0))

ValueError: operands could not be broadcast together with shapes (10,25,25) (3,) 