In [1]:
import numpy as np

In [2]:
a = np.random.randint(50, size = (1000, ))
ans = np.zeros((1000,))
ans[np.random.randint(low = 0, high = 1000)] = 1
print(np.argmax(ans))

289


In [3]:
b = -np.sum(np.log(np.exp(a)/np.sum(np.exp(a), axis = 0)) * ans, axis = 0)
print(b, ans, ans*b)

5.576880926639509 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [4]:
%timeit -n 15000 k = -np.sum(np.log(np.exp(a)/np.sum(np.exp(a), axis = 0)), axis = 0)
%timeit -n 15000 k = -np.log(np.exp(a) / np.sum(np.exp(a), axis = 0))[np.argmax(ans)]

26 µs ± 139 ns per loop (mean ± std. dev. of 7 runs, 15000 loops each)
25 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 15000 loops each)


In [10]:
N = 10
D = 20
H = 25
C = 15
bef_input = np.random.random((N, D))
bef_weight = np.random.random((D, H))
bef_bias = np.random.random((H, ))

In [6]:
kk = np.ones((N, ))
aft_input = np.concatenate((bef_input, kk.reshape(-1, 1)), axis = 1)
aft_weight = np.concatenate((bef_weight, bef_bias.reshape(1, -1)), axis = 0)
aa = np.matmul(aft_input, aft_weight)
bb = np.matmul(bef_input, bef_weight) + bef_bias.T
# aa = np.zeros(())
# bb = np.arange(4, 10).reshape(2, -1)
# bb.shape

In [7]:
k = np.random.randint(10, size = (10, 10))
ans = np.random.randint(0, 10, size = 10)

In [8]:
print(k, ans)
np.sum(k[np.arange(k.shape[0]), ans], axis = 0)

[[0 4 3 1 0 0 9 5 3 4]
 [9 8 1 0 0 0 4 4 5 9]
 [7 4 4 1 3 6 5 2 4 3]
 [4 9 3 3 3 7 4 5 1 6]
 [9 7 5 0 7 4 3 5 7 3]
 [0 2 6 0 0 6 2 1 1 5]
 [2 7 9 0 0 2 7 5 8 3]
 [7 3 8 1 6 5 1 4 5 7]
 [5 9 4 8 7 8 9 0 2 9]
 [1 8 8 3 6 6 0 0 9 8]] [4 1 7 5 1 3 8 5 4 0]


45

In [21]:
scores_bef = np.random.randint(0, 20, size = (N, C))
y = np.random.randint(C, size = (N, ))
scores_bef, y

(array([[19,  7, 18, 12, 14,  6, 12,  4,  1,  0,  8,  3,  3,  8,  8],
        [15,  5, 18,  8,  6, 10,  3, 11, 16, 14,  9,  1,  4, 14, 14],
        [ 9, 10,  4,  9, 18, 14,  1, 18,  7, 10,  3, 19,  5,  4,  8],
        [19, 18, 16, 13, 16,  9,  3,  6,  5,  5,  0, 11, 16,  8, 17],
        [ 1,  3, 10, 13,  2,  8,  8, 18, 18, 17,  1,  3,  0,  9,  6],
        [14,  6, 17, 12,  2, 13,  1, 11, 16, 14, 10,  6, 11, 15, 14],
        [ 1,  1,  3,  0, 16,  7, 19, 10,  0, 11, 10, 18,  9,  9, 17],
        [ 1, 14, 19, 16, 11,  8, 12,  1,  9,  4,  6, 16, 17, 18, 11],
        [ 0,  0, 10,  0, 17, 12,  3, 13, 14,  9,  9, 10,  0,  6, 16],
        [13, 18, 14, 18, 13,  8, 18, 15, 14,  0, 14, 16,  5, 18,  9]]),
 array([11,  6,  1,  6,  2,  6, 14,  2, 11,  7]))

In [23]:
scores_bef[np.arange(N), y]

array([ 3,  3, 10,  3, 10,  1, 17, 19, 10, 15])

In [41]:
qq = np.random.randint(10, size = (N-7, C-12))
pp = np.random.randint(10, size = (N-7, H-20))
print(qq, pp, sep = '\n')

[[5 9 9]
 [1 7 2]
 [3 7 2]]
[[1 8 8 7 1]
 [6 4 3 4 5]
 [4 1 4 9 1]]


In [128]:
qqq = np.random.randint(10, size = (5, 6, 7))
ppp = np.random.randint(10, size = (5, 7))
print(np.einsum('ijk, ik -> ij', qqq, ppp).shape)
vv = np.random.randint(0, 5, size = 3)
# vv

(5, 6)


In [125]:
aas = np.where(qq>=7)
print(aas, qqq[aas[0], aas[1], aas[1]], qqq, sep = '\n')

(array([0, 0, 1, 2]), array([1, 2, 1, 1]))
[0 7 2 7]
[[[7 3 6 5 9]
  [1 0 1 1 6]
  [3 5 7 8 9]
  [9 8 1 8 2]
  [9 3 3 3 5]]

 [[2 3 3 0 0]
  [5 2 0 4 1]
  [6 9 9 7 0]
  [2 8 3 3 0]
  [2 7 9 8 0]]

 [[8 7 2 4 5]
  [6 7 1 0 7]
  [5 7 4 7 7]
  [8 1 1 2 2]
  [8 2 8 2 4]]

 [[5 1 1 6 6]
  [1 2 2 2 0]
  [9 5 3 5 0]
  [5 3 3 2 2]
  [9 5 9 0 2]]

 [[0 3 5 9 1]
  [2 4 6 5 7]
  [6 4 5 0 4]
  [8 9 7 5 0]
  [1 9 0 5 9]]]


In [43]:
t = np.einsum('ij, ik -> ijk', pp, qq)
print(t, t.shape, sep = '\n')

[[[ 5  9  9]
  [40 72 72]
  [40 72 72]
  [35 63 63]
  [ 5  9  9]]

 [[ 6 42 12]
  [ 4 28  8]
  [ 3 21  6]
  [ 4 28  8]
  [ 5 35 10]]

 [[12 28  8]
  [ 3  7  2]
  [12 28  8]
  [27 63 18]
  [ 3  7  2]]]
(3, 5, 3)


In [47]:
ttv = np.einsum('ij, ik -> ikj', qq, pp)
print(ttv, ttv.shape, sep = '\n')

[[[ 5  9  9]
  [40 72 72]
  [40 72 72]
  [35 63 63]
  [ 5  9  9]]

 [[ 6 42 12]
  [ 4 28  8]
  [ 3 21  6]
  [ 4 28  8]
  [ 5 35 10]]

 [[12 28  8]
  [ 3  7  2]
  [12 28  8]
  [27 63 18]
  [ 3  7  2]]]
(3, 5, 3)


In [45]:
np.sum(t, axis = 0).shape

(5, 3)

In [139]:
tts = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
ttss = np.exp(tts) / np.sum(np.exp(tts), axis = 0)
-np.log(ttss)[0]

4.451914395937593